// SETUP INSTRUCTIONS:
// 1. Go to https://console.firebase.google.com
// 2. Create a new project named "pharma-wholesale"
// 3. Add an Android app with package name: com.pharma.wholesale
// 4. Download google-services.json and place it in android/app/
// 5. Run: flutterfire configure
// 6. This file will be auto-generated. Replace this file with the generated one.

// File: lib/firebase_options.dart
// This file is generated by FlutterFire CLI.
// Run: dart pub global activate flutterfire_cli
//      flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not supported');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  // ⚠️  REPLACE THESE VALUES WITH YOUR OWN FROM FIREBASE CONSOLE
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY_HERE',
    appId: 'YOUR_APP_ID_HERE',
    messagingSenderId: 'YOUR_SENDER_ID_HERE',
    projectId: 'YOUR_PROJECT_ID_HERE',
    storageBucket: 'YOUR_STORAGE_BUCKET_HERE',
  );
}
